# Generated by Django 5.2.9 on 2026-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='iter', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='id_proof',
            field=models.ImageField(default='none', upload_to='seller/id_proof'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default='aa', max_length=30),
            preserve_default=False,
        ),
    ]
