# Generated by Django 5.2.9 on 2026-02-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_seller_address_seller_id_proof_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
