# Generated by Django 5.2.9 on 2026-02-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_seller_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='seller/id_proof'),
        ),
    ]
