# Generated by Django 5.2.9 on 2026-02-10 06:25

import Seller.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_remove_seller_username_alter_seller_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
                ('objects', Seller.models.SellerManager()),
            ],
        ),
    ]
